[package]
name = "calc-ind"
version = "0.1.0"
edition = "2021"

[lib]
name = "calc_ind"

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust_decimal = { workspace = true }
ferro_ta_core = { workspace = true }
reqwest = { workspace = true }
ohlcv-engine = { version = "0.1.0", path = "../ohlcv-engine" }
transport = { path = "../../cycle-engine/transport" }
infra = { path = "../../cycle-engine/infra" }
